/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MediaCompanion
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  hideSidecar: true,
  extensions: [
    "png",
    "jpg",
    "jpeg",
    "bmp",
    "avif",
    "webp",
    "gif",
    "mp4",
    "webm",
    "ogv",
    "mov"
  ],
  sidecarTemplate: "",
  apiEnabled: false,
  apiPort: 27124,
  apiKey: "",
  fullscreenMode: "hover",
  fullscreenHoverDelay: 1e3
};

// src/cache.ts
var import_obsidian = require("obsidian");

// src/model/sidecar.ts
var _Sidecar = class _Sidecar {
  constructor() {
  }
  /**
      * Create a new sidecar file and link it to a media file
      * @param file The media file to link it to
      * @param app The app instance
      * @returns The created sidecar
      */
  static async create(mediaFile, app, plugin, f = null) {
    const file = new _Sidecar();
    file.mediaFile = mediaFile;
    file.app = app;
    file.plugin = plugin;
    await file.fill(f);
    return file;
  }
  /**
      * Fill the sidecar with its metadata
      * @param file The media file to use for filling
      * @param app The app instance
      */
  async fill(f = null) {
    if (f) {
      this.file = f;
    } else {
      this.file = await this.createIfNotExists();
    }
    this.hideInAll();
  }
  /**
      * Create a sidecar file if it does not exist yet
      * @param app The app instance
      * @returns The already existing or newly created sidecar file
      */
  async createIfNotExists() {
    var _a;
    const file = (_a = this.app.vault.getFileByPath(`${this.mediaFile.path}${_Sidecar.EXTENSION}`)) != null ? _a : await this.app.vault.create(`${this.mediaFile.path}${_Sidecar.EXTENSION}`, this.plugin.settings.sidecarTemplate);
    return file;
  }
  hideInAll() {
    const leaves = this.app.workspace.getLeavesOfType("file-explorer");
    for (const leaf of leaves) {
      this.hide(leaf);
    }
  }
  /**
   * Hides a sidecar from a given file explorer leaf
   * @param leaf The file explorer leaf the sidecar should be hidden form
   */
  hide(leaf) {
    var _a, _b, _c;
    if (!leaf) return;
    if (!((_a = leaf.view) == null ? void 0 : _a.fileItems)) return;
    const element = (_c = (_b = leaf.view) == null ? void 0 : _b.fileItems[this.file.path]) == null ? void 0 : _c.el;
    if (!element) return;
    element.hidden = this.plugin.settings.hideSidecar;
  }
  /**
      * Finds all tags in the file: Both the frontmatter and the body, and returns
      * them without duplicates and hashtags.
      * @returns The tags, without hashtags and duplicates
      */
  getTags() {
    var _a, _b, _c, _d;
    const cache = this.app.metadataCache.getFileCache(this.file);
    if (!cache) return [];
    let tags = (_b = (_a = cache.tags) == null ? void 0 : _a.map((t) => t.tag)) != null ? _b : [];
    const fmTags = (_d = (_c = cache.frontmatter) == null ? void 0 : _c.tags) != null ? _d : [];
    if (Array.isArray(fmTags)) {
      tags = tags.concat(fmTags);
    } else {
      tags.push(fmTags);
    }
    tags = tags.map((t) => t.toLowerCase());
    tags = [...new Set(tags)];
    return tags.map((t) => t.startsWith("#") ? t.slice(1) : t);
  }
  /**
      * Gets the information from a tag in the frontmatter
      * @param tag The tag to get from the frontmatter
      * @returns The data in the tag, or undefined if it does not exist
      */
  getFrontmatterTag(tag) {
    var _a;
    const cache = (_a = this.app.metadataCache.getFileCache(this.file)) == null ? void 0 : _a.frontmatter;
    if (!cache) return void 0;
    return cache[tag];
  }
  /** 
      * Sets the information in a tag in the frontmatter
      * @param tag The tag to set in the frontmatter
      * @param value The value to set
      * @param type The type of the frontmatter tag
      */
  async setFrontmatterTag(tag, value, type = void 0) {
    try {
      await this.app.fileManager.processFrontMatter(this.file, (fm) => fm[tag] = value);
      if (type) {
        this.app.metadataTypeManager.properties[tag.toLowerCase()].type = type;
      }
    } catch (e) {
      console.error(e);
    }
  }
};
_Sidecar.EXTENSION = ".sidecar.md";
var Sidecar = _Sidecar;

// src/model/types/mediaTypes.ts
function getMediaType(extension) {
  switch (extension.toLowerCase()) {
    case "png":
    case "jpg":
    case "jpeg":
    case "webp":
    case "avif":
    case "bmp":
    case "gif":
      return "image" /* Image */;
    case "mp4":
    case "webm":
    case "ogv":
    case "mov":
      return "video" /* Video */;
    default:
      return "unknown" /* Unknown */;
  }
}

// src/model/mediaFile.ts
var _MediaFile = class _MediaFile {
  constructor() {
  }
  /**
      * Create a new MediaFile from a binary file
      * @param file The file to create a MediaFile from
      * @param app The app instance
   * @param sidecar The sidecar for the file, in case it already exists
      * @returns The created MediaFile
      */
  static async create(file, app, plugin, sidecar = null) {
    const f = new _MediaFile();
    await _MediaFile.fill(f, file, app, plugin, sidecar);
    return f;
  }
  /**
      * Fill the variables of the MediaFile
      * @param f The MediaFile to fill
      * @param file The related binary file
      * @param app The app instance
   * @param sidecar The sidecar for the file, in case it already exists
      */
  static async fill(f, file, app, plugin, sidecar = null) {
    f.file = file;
    f.app = app;
    f.plugin = plugin;
    f.sidecar = await Sidecar.create(file, app, plugin, sidecar);
    await f.update();
  }
  /**
   * Finds the mediaType of the file based on the extension of the file
   * @returns The MediaType of the file
   */
  getType() {
    return getMediaType(this.file.extension);
  }
  /**
      * To be called when a file has been updated
      */
  async update() {
    const last_updated = this.sidecar.getFrontmatterTag(_MediaFile.last_updated_tag);
    if (!last_updated || last_updated < this.file.stat.mtime) {
      await this.sidecar.setFrontmatterTag(_MediaFile.last_updated_tag, /* @__PURE__ */ new Date(), "datetime");
    }
  }
};
_MediaFile.last_updated_tag = "MC-last-updated";
var MediaFile = _MediaFile;

// node_modules/extract-colors/lib/extract-colors.mjs
var Color = class _Color {
  /**
   * Set red, green and blue colors to create the Color object.
   */
  constructor(red, green, blue, hex = red << 16 | green << 8 | blue) {
    this._count = 1;
    this.__saturation = -1;
    this.__hue = -1;
    this.__lightness = -1;
    this.__intensity = -1;
    this._red = red;
    this._green = green;
    this._blue = blue;
    this._hex = hex;
  }
  /**
   * Distance between two colors.
   * - Minimum is 0 (between two same colors)
   * - Maximum is 1 (for example between black and white)
   */
  static distance(colorA, colorB) {
    return (Math.abs(colorB._red - colorA._red) + Math.abs(colorB._green - colorA._green) + Math.abs(colorB._blue - colorA._blue)) / (3 * 255);
  }
  clone() {
    const color = new _Color(this._red, this._green, this._blue, this._hex);
    color._count = this._count;
    return color;
  }
  updateHSL() {
    const red = this._red / 255;
    const green = this._green / 255;
    const blue = this._blue / 255;
    const max = Math.max(red, green, blue);
    const min = Math.min(red, green, blue);
    this.__lightness = (max + min) / 2;
    if (max === min) {
      this.__hue = 0;
      this.__saturation = 0;
      this.__intensity = 0;
    } else {
      const distance2 = max - min;
      this.__saturation = this.__lightness > 0.5 ? distance2 / (2 - max - min) : distance2 / (max + min);
      this.__intensity = this.__saturation * ((0.5 - Math.abs(0.5 - this.__lightness)) * 2);
      switch (max) {
        case red:
          this.__hue = ((green - blue) / distance2 + (green < blue ? 6 : 0)) / 6;
          break;
        case green:
          this.__hue = ((blue - red) / distance2 + 2) / 6;
          break;
        case blue:
          this.__hue = ((red - green) / distance2 + 4) / 6;
          break;
      }
    }
  }
  /**
   * Hue from 0 to 1
   */
  get _hue() {
    if (this.__hue === -1) {
      this.updateHSL();
    }
    return this.__hue;
  }
  /**
   * Saturation from 0 to 1
   */
  get _saturation() {
    if (this.__saturation === -1) {
      this.updateHSL();
    }
    return this.__saturation;
  }
  /**
   * Lightness from 0 to 1
   */
  get _lightness() {
    if (this.__lightness === -1) {
      this.updateHSL();
    }
    return this.__lightness;
  }
  /**
   * Color intensity from 0 to 1
   */
  get _intensity() {
    if (this.__intensity === -1) {
      this.updateHSL();
    }
    return this.__intensity;
  }
};
var distance = (a, b) => Math.abs(a - b);
var hueDistance = (a, b) => Math.min(distance(a, b), distance((a + 0.5) % 1, (b + 0.5) % 1));
var AverageGroup = class {
  constructor() {
    this.colors = [];
    this._average = null;
  }
  addColor(color) {
    this.colors.push(color);
    this._average = null;
  }
  isSamePalette(color, hue, saturation, lightness) {
    for (let i = 0; i < this.colors.length; i++) {
      const currentColor = this.colors[i];
      const isSame = hueDistance(currentColor._hue, color._hue) < hue && distance(currentColor._saturation, color._saturation) < saturation && distance(currentColor._lightness, color._lightness) < lightness;
      if (!isSame) {
        return false;
      }
    }
    return true;
  }
  get average() {
    if (!this._average) {
      const { r, g, b } = this.colors.reduce((total2, color) => {
        total2.r += color._red;
        total2.g += color._green;
        total2.b += color._blue;
        return total2;
      }, { r: 0, g: 0, b: 0 });
      const total = this.colors.reduce((_count, color) => _count + color._count, 0);
      this._average = new Color(
        Math.round(r / this.colors.length),
        Math.round(g / this.colors.length),
        Math.round(b / this.colors.length)
      );
      this._average._count = total;
    }
    return this._average;
  }
};
var AverageManager = class {
  constructor(hue, saturation, lightness) {
    this._groups = [];
    this._hue = hue;
    this._saturation = saturation;
    this._lightness = lightness;
  }
  addColor(color) {
    const samePalette = this._groups.find((averageGroup) => averageGroup.isSamePalette(color, this._hue, this._saturation, this._lightness));
    if (samePalette) {
      samePalette.addColor(color);
    } else {
      const averageGroup = new AverageGroup();
      averageGroup.addColor(color);
      this._groups.push(averageGroup);
    }
  }
  getGroups() {
    return this._groups.map((averageGroup) => averageGroup.average);
  }
};
var sortColors = (list, _pixels, _hueDistance, _saturationDistance, _lightnessDistance) => {
  const averageManager = new AverageManager(_hueDistance, _saturationDistance, _lightnessDistance);
  list.forEach((color) => averageManager.addColor(color));
  const sorted = averageManager.getGroups();
  sorted.sort((a, b) => {
    const bPower = (b._intensity + 0.1) * (0.9 - b._count / _pixels);
    const aPower = (a._intensity + 0.1) * (0.9 - a._count / _pixels);
    return bPower - aPower;
  });
  return sorted;
};
var createFinalColor = (color, pixels) => {
  return {
    hex: `#${"0".repeat(6 - color._hex.toString(16).length)}${color._hex.toString(16)}`,
    red: color._red,
    green: color._green,
    blue: color._blue,
    area: color._count / pixels,
    hue: color._hue,
    saturation: color._saturation,
    lightness: color._lightness,
    intensity: color._intensity
  };
};
var cleanInputs = ({
  pixels = 64e3,
  distance: distance2 = 0.22,
  colorValidator = (_red, _green, _blue, _alpha) => (_alpha != null ? _alpha : 255) > 250,
  hueDistance: hueDistance2 = 0.08333333333333333,
  saturationDistance = 0.2,
  lightnessDistance = 0.2,
  crossOrigin = null
} = {}) => {
  if (true) {
    const testUint = (label, val, min = 0, max = Number.MAX_SAFE_INTEGER) => {
      if (!Number.isInteger(val)) {
        throw new Error(`${label} is not a valid number (${val})`);
      }
      if (val < min) {
        console.warn(`${label} can not be less than ${min} (it's ${val})`);
      }
      if (val > max) {
        console.warn(`${label} can not be more than ${max} (it's ${val})`);
      }
      return Math.min(Math.max(val, min), max);
    };
    const testNumber = (label, val, min = 0, max = Number.MAX_VALUE) => {
      if (Number(val) !== val) {
        throw new Error(`${label} is not a valid number (${val})`);
      }
      if (val < min) {
        console.warn(`${label} can not be less than ${min} (it's ${val})`);
      }
      if (val > max) {
        console.warn(`${label} can not be more than ${max} (it's ${val})`);
      }
      return Math.min(Math.max(val, min), max);
    };
    const testFunction = (label, val) => {
      if (!val || {}.toString.call(val) !== "[object Function]") {
        throw new Error(`${label} is not a function (${val})`);
      }
      return val;
    };
    testUint("pixels", pixels || 0, 1);
    testNumber("distance", distance2, 0, 1);
    testFunction("colorValidator", colorValidator);
    testNumber("hueDistance", hueDistance2, 0, 1);
    testNumber("saturationDistance", saturationDistance, 0, 1);
    testNumber("lightnessDistance", lightnessDistance, 0, 1);
  }
  return [
    Math.max(pixels, 1),
    Math.min(Math.max(distance2, 0), 1),
    colorValidator,
    Math.min(Math.max(hueDistance2, 0), 1),
    Math.min(Math.max(saturationDistance, 0), 1),
    Math.min(Math.max(lightnessDistance, 0), 1),
    crossOrigin
  ];
};
var LeafGroup = class {
  /**
   * Store colors or groups and _count similiar groups in the image.
   */
  constructor() {
    this._count = 0;
    this._children = {};
  }
  /**
   * Add color to the group.
   * 
   * @param _hex Hexadecimal value of the color
   * @param _red Red chanel amount of the color
   * @param _green Green chanel amount of the color
   * @param _blue Blue chanel amount of the color
   * @returns The color
   */
  addColor(_hex, _red, _green, _blue) {
    this._count++;
    if (this._children[_hex]) {
      this._children[_hex]._count++;
    } else {
      this._children[_hex] = new Color(_red, _green, _blue, _hex);
    }
    return this._children[_hex];
  }
  /**
   * Get list of groups of list of colors.
   * 
   * @returns List of colors
   */
  getList() {
    return Object.keys(this._children).map((key) => this._children[key]);
  }
  /**
   * Representative color of leaf.
   * 
   * @returns Main color of the leaf
   */
  createMainColor() {
    const list = this.getList();
    const biggest = list.reduce((a, b) => a._count >= b._count ? a : b);
    const main = biggest.clone();
    main._count = this._count;
    return main;
  }
};
var RootGroup = class {
  /**
   * Store colors or groups and _count similiar groups in the image.
   */
  constructor() {
    this._count = 0;
    this._children = {};
  }
  /**
   * Get list of groups of list of colors.
   */
  getList() {
    return Object.keys(this._children).map((key) => this._children[key]);
  }
  addColor(r, g, b) {
    const full = r << 16 | g << 8 | b;
    const loss = (r >> 4 & 15) << 8 | (g >> 4 & 15) << 4 | b >> 4 & 15;
    this._count++;
    return this.getLeafGroup(loss).addColor(full, r, g, b);
  }
  /**
   * Add a key for a color, this key is a simplification to find neighboring colors.
   * Neighboring colors has same key.
   */
  getLeafGroup(key) {
    if (!this._children[key]) {
      this._children[key] = new LeafGroup();
    }
    return this._children[key];
  }
  /**
   * List of colors sorted by importance (neighboring hare calculated by distance and removed).
   * Importance is calculated with the saturation and _count of neighboring colors.
   */
  getColors(_distance) {
    const list = this.getList().map((child) => child.createMainColor());
    list.sort((a, b) => b._count - a._count);
    const newList = [];
    while (list.length) {
      const current = list.shift();
      list.filter((color) => Color.distance(current, color) < _distance).forEach((near) => {
        current._count += near._count;
        const i = list.findIndex((color) => color === near);
        list.splice(i, 1);
      });
      newList.push(current);
    }
    return newList;
  }
};
var extractor = ({ data, width, height }, _pixels, _distance, _colorValidator) => {
  const colorGroup = new RootGroup();
  const reducer = width && height ? Math.floor(width * height / _pixels) || 1 : 1;
  let ignoredColorsCount = 0;
  for (let i = 0; i < data.length; i += 4 * reducer) {
    const r = data[i];
    const g = data[i + 1];
    const b = data[i + 2];
    const a = data[i + 3];
    if (_colorValidator(r, g, b, a)) {
      colorGroup.addColor(r, g, b);
    } else {
      ignoredColorsCount++;
    }
  }
  return {
    colors: colorGroup.getColors(_distance),
    count: colorGroup._count + ignoredColorsCount
  };
};
var _isBrowser = () => typeof window !== "undefined";
var _sortFinalColors = (_colors, _pixels, _hueDistance, _saturationDistance, _lightnessDistance) => {
  const list = sortColors(_colors, _pixels, _hueDistance, _saturationDistance, _lightnessDistance);
  return list.map((color) => createFinalColor(color, _pixels));
};
var _getImageData = (_image, _pixels) => {
  const currentPixels = _image.width * _image.height;
  const width = currentPixels < _pixels ? _image.width : Math.round(_image.width * Math.sqrt(_pixels / currentPixels));
  const height = currentPixels < _pixels ? _image.height : Math.round(_image.height * Math.sqrt(_pixels / currentPixels));
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const context = canvas.getContext("2d");
  context.drawImage(_image, 0, 0, _image.width, _image.height, 0, 0, width, height);
  return context.getImageData(0, 0, width, height);
};
var extractColorsFromImageData = (imageData, options = {}) => {
  const [_pixels, _distance, _colorValidator, _hueDistance, _saturationDistance, _lightnessDistance] = cleanInputs(options);
  const { colors, count } = extractor(imageData, _pixels, _distance, _colorValidator);
  return _sortFinalColors(colors, count, _hueDistance, _saturationDistance, _lightnessDistance);
};
var extractColorsFromImage = (image, options = {}) => {
  if (_isBrowser()) {
    const [_pixels, _distance, _colorValidator, _hueDistance, _saturationDistance, _lightnessDistance, _crossOrigin] = cleanInputs(options);
    image.crossOrigin = _crossOrigin;
    return new Promise((resolve) => {
      const extract = (image2) => {
        const imageData = _getImageData(image2, _pixels);
        const { colors, count } = extractor(imageData, _pixels, _distance, _colorValidator);
        resolve(_sortFinalColors(colors, count, _hueDistance, _saturationDistance, _lightnessDistance));
      };
      if (image.complete) {
        extract(image);
      } else {
        const imageLoaded = () => {
          image.removeEventListener("load", imageLoaded);
          extract(image);
        };
        image.addEventListener("load", imageLoaded);
      }
    });
  } else {
    if (true) {
      throw new Error("Can not use extractColorsFromImage for Node.js");
    }
  }
};
var extractColorsFromSrc = (src, options = {}) => {
  if (_isBrowser()) {
    const image = new Image();
    image.src = src;
    return extractColorsFromImage(image, options);
  } else {
    if (true) {
      throw new Error("Can not use extractColorsFromSrc for Node.js");
    }
  }
};
var extractColors = (picture, options) => {
  if (_isBrowser()) {
    if (picture instanceof Image) {
      return extractColorsFromImage(picture, options);
    }
    if (picture instanceof ImageData || picture instanceof Object && picture.data) {
      return new Promise((resolve) => {
        resolve(extractColorsFromImageData(picture, options));
      });
    }
    if (typeof picture === "string") {
      return extractColorsFromSrc(picture, options);
    }
  } else {
    if (true) {
      if (picture instanceof String) {
        throw new Error("Send imageData to extractColors (Image src or HTMLImageElement not supported in Nodejs)");
      }
      if (!picture.data) {
        throw new Error("Send imageData to extractColors");
      }
      if (options == null ? void 0 : options.crossOrigin) {
        console.warn("options.crossOrigin not supported in Node.js");
      }
    }
    return new Promise((resolve) => {
      resolve(extractColorsFromImageData(picture, options));
    });
  }
  throw new Error(`Can not analyse picture`);
};

// src/model/types/image/image.ts
var _MCImage = class _MCImage extends MediaFile {
  constructor() {
    super();
  }
  /**
      * Create a new MCImage from a file: Use as constructor
      * @param file The file to create the image from
      * @param app The app instance
   * @param sidecar The sidecar file, if it already exists
      * @returns The created MCImage
      */
  static async create(file, app, plugin, sidecar = null) {
    const f = new _MCImage();
    await _MCImage.fill(f, file, app, plugin, sidecar);
    return f;
  }
  /**
      * Fill the properties of a file
      * @param f The file to fill
      * @param file The related binary file
      * @param app The app instance
   * @param sidecar The sidecar file, if it already exists
      */
  static async fill(f, file, app, plugin, sidecar = null) {
    await super.fill(f, file, app, plugin, sidecar);
  }
  /**
      * Extracts the colors from the image file
      * @returns The colors, in the format dictated by the extract-colors package
      */
  async readColors() {
    const extracted = await extractColors(
      this.app.vault.getResourcePath(this.file),
      // 1/4th of default pixels to speed up the process
      { pixels: 16e3 }
    );
    const colors = [];
    for (const e of extracted) {
      colors.push({
        h: e.hue,
        s: e.saturation,
        l: e.lightness,
        area: e.area
      });
    }
    return colors;
  }
  /**
   * Finds the cached colors of the image. If they aren't already registered,
   * they will be extracted and saved when this is called.
   * @returns The cached colors of the image
   */
  async getCachedColors() {
    if (!this.sidecar.getFrontmatterTag(_MCImage.colors_tag)) {
      await this.setColors();
    }
    return this.sidecar.getFrontmatterTag(_MCImage.colors_tag);
  }
  /**
   * Extracts and sets the colors for the image
   */
  async setColors() {
    const colors = await this.readColors();
    await this.sidecar.setFrontmatterTag(_MCImage.colors_tag, colors);
  }
  /**
      * Attempts to parse the given object as an array wit [width, height]. 
      * Returns undefined if failed
      * @param size An object potentially holding the width and height of an image
      * @returns The width and height object, undefined if not present
      */
  static parseSize(size) {
    if (!(size instanceof Array)) return void 0;
    if (size.length !== 2) return void 0;
    return { width: size[0], height: size[1] };
  }
  /**
      * Read the width and height from a binary image
      * @returns The size of the image
      */
  async readSize() {
    const image = new Image();
    image.src = this.app.vault.getResourcePath(this.file);
    await image.decode();
    return { width: image.naturalWidth, height: image.naturalHeight };
  }
  /**
   * Finds and returns the size of the image in pixels.
   * If there is no size in the cache yet, this will be computed when this is called.
   * @returns The cached size
   */
  async getCachedSize() {
    const value = this.sidecar.getFrontmatterTag(_MCImage.size_tag);
    if (!value || !_MCImage.parseSize(value)) {
      await this.setSize();
    }
    return _MCImage.parseSize(this.sidecar.getFrontmatterTag(_MCImage.size_tag));
  }
  /**
   * Finds and sets the size of the image to the cache
   */
  async setSize() {
    const size = await this.readSize();
    await this.sidecar.setFrontmatterTag(_MCImage.size_tag, [size.width, size.height]);
  }
  /**
      * To be called when the file is updated
      */
  async update() {
    const last_updated = this.sidecar.getFrontmatterTag(MediaFile.last_updated_tag);
    await this.getCachedColors();
    await this.getCachedSize();
    if (!last_updated || last_updated < this.file.stat.mtime) {
      await this.setColors();
      await this.setSize();
    }
    await super.update();
  }
};
// The reserved tags for this type
// when editing these, they should also be renamed in
// frontmatter.ts
_MCImage.size_tag = "MC-size";
_MCImage.colors_tag = "MC-colors";
var MCImage = _MCImage;

// src/cache.ts
var Cache = class {
  constructor(app, plugin) {
    this.paths = {};
    this.tags = {};
    this.extensions = {};
    // Whether there is files currently being added or removed from the cache
    this.building = false;
    this.initialized = false;
    this.files = [];
    this.app = app;
    this.plugin = plugin;
  }
  /**
   * Will wait in steps of 100ms until the cache is initialized
   */
  async awaitReady() {
    await this.initialize();
    if (this.building || !this.initialized) {
      while (this.building || !this.initialized) {
        await new Promise((resolve) => setTimeout(resolve, 100));
      }
    }
  }
  /**
      * Initialize the cache with all the (supported) files in the vault
      */
  async initialize() {
    if (this.initialized) return;
    if (this.building) {
      while (this.building) {
        await new Promise((resolve) => setTimeout(resolve, 100));
      }
      return;
    }
    this.building = true;
    while (this.app.metadataCache.inProgressTaskCount > 0) {
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
    let files = this.app.vault.getFiles();
    const timer = Date.now();
    const total_files = files.length;
    files = files.filter((f) => this.plugin.settings.extensions.contains(f.extension.toLowerCase()));
    console.debug(
      `%c[Media Companion]: %cBuilding cache with ${files.length} media files found of ${total_files} files total 
                   If this is the first time, this may take a while`,
      "color: #00b7eb",
      "color: inherit"
    );
    const notice = new import_obsidian.Notice(`Building cache with ${files.length} media files found of ${total_files} files total
Processing may take a while if many new files have been added`, 0);
    let total_done = 0;
    for (const file of files) {
      let mediaFile;
      try {
        switch (getMediaType(file.extension)) {
          case "image" /* Image */:
            mediaFile = await MCImage.create(file, this.app, this.plugin);
            break;
          case "video" /* Video */:
          case "unknown" /* Unknown */:
          default:
            mediaFile = await MediaFile.create(file, this.app, this.plugin);
            break;
        }
        this.addFile(mediaFile);
      } catch (e) {
        console.log(`Failed on ${file.name}`);
        console.log(e);
      }
      total_done++;
      notice.setMessage(`Media Companion: ${total_done}/${files.length} files processed
Processing may take a while if many new files have been added`);
    }
    notice.hide();
    console.debug(
      `%c[Media Companion]: %cFinished building cache in ${(Date.now() - timer) / 1e3}s, ${this.files.length} files in cache`,
      "color: #00b7eb",
      "color: inherit"
    );
    this.initialized = true;
    this.building = false;
  }
  /**
   * Will add new files to the cache or remove unneeded ones.
   * Should be called whenever plugin.settings.extensions is changed.
   */
  async updateExtensions() {
    if (this.building) {
      while (this.building) {
        await new Promise((resolve) => setTimeout(resolve, 100));
      }
    }
    this.building = true;
    this.files = this.files.filter((f) => this.plugin.settings.extensions.contains(f.file.extension.toLowerCase()));
    let files = this.app.vault.getFiles();
    files = files.filter((f) => this.plugin.settings.extensions.contains(f.extension.toLowerCase()));
    files = files.filter((f) => !this.files.some((mf) => mf.file.path === f.path));
    const notice = new import_obsidian.Notice(`Adding ${files.length} new files`, 0);
    let total_done = 0;
    for (const file of files) {
      let mediaFile;
      switch (getMediaType(file.extension)) {
        case "image" /* Image */:
          mediaFile = await MCImage.create(file, this.app, this.plugin);
          break;
        case "video" /* Video */:
        case "unknown" /* Unknown */:
        default:
          mediaFile = await MediaFile.create(file, this.app, this.plugin);
          break;
      }
      this.addFile(mediaFile);
      total_done++;
      notice.setMessage(`Media Companion: ${total_done}/${files.length} new files added
Processing may take a while if many new files have been added`);
    }
    notice.hide();
    this.building = false;
  }
  /**
      * Add a file to the cache
      * @param file The file to add to the cache
      */
  addFile(file) {
    var _a, _b;
    this.files.push(file);
    if ((_a = file.file.parent) == null ? void 0 : _a.path) {
      for (const path of this.getPathHierarchy((_b = file.file.parent) == null ? void 0 : _b.path)) {
        this.addCounter(this.paths, path);
      }
    }
    this.addCounter(this.extensions, file.file.extension);
    const tags = file.sidecar.getTags();
    if (tags.length > 0) {
      for (const tag of tags) {
        for (const path of this.getPathHierarchy(tag)) {
          this.addCounter(this.tags, path);
        }
      }
    }
  }
  /**
      * Remove a file from the cache
      * @param file The file to remove
      * @returns Whether the operation removed a file or not
      */
  removeFile(file) {
    var _a, _b;
    const mediaFile = this.files.find((f) => f.file === file);
    if (mediaFile) {
      this.files = this.files.filter((f) => f.file !== file);
      if ((_a = mediaFile.file.parent) == null ? void 0 : _a.path) {
        for (const path of this.getPathHierarchy((_b = mediaFile.file.parent) == null ? void 0 : _b.path)) {
          this.removeCounter(this.paths, path);
        }
      }
      this.removeCounter(this.extensions, mediaFile.file.extension);
      const tags = mediaFile.sidecar.getTags();
      if (tags.length > 0) {
        for (const tag of tags) {
          for (const path of this.getPathHierarchy(tag)) {
            this.removeCounter(this.tags, path);
          }
        }
      }
      return true;
    }
    return false;
  }
  fileMoved(file, oldPath) {
    var _a, _b;
    if ((_a = file.file.parent) == null ? void 0 : _a.path) {
      for (const path of this.getPathHierarchy((_b = file.file.parent) == null ? void 0 : _b.path)) {
        this.addCounter(this.paths, path);
      }
    }
    for (const path of this.getPathHierarchy(oldPath)) {
      this.removeCounter(this.paths, path);
    }
  }
  sidecarUpdated(_) {
    this.tags = {};
    for (const mFile of this.files) {
      for (const tag of mFile.sidecar.getTags()) {
        for (const path of this.getPathHierarchy(tag)) {
          this.addCounter(this.tags, path);
        }
      }
    }
  }
  addCounter(counter, value) {
    if (counter[value]) {
      counter[value] += 1;
    } else {
      counter[value] = 1;
    }
  }
  removeCounter(counter, value) {
    if (counter[value]) {
      counter[value] -= 1;
      if (counter[value] == 0) {
        delete counter[value];
      }
    }
  }
  /**
   * Returns all parent paths for a given path, from root to full path
   * @param path The file path to process
   * @returns Array of path strings, from root to full path
   */
  getPathHierarchy(path) {
    if (!path) return [""];
    const segments = path.split("/");
    const paths = [];
    let currentPath = "";
    for (let i = 0; i < segments.length; i++) {
      if (currentPath && segments[i]) {
        currentPath += "/";
      }
      currentPath += segments[i];
      if (currentPath) {
        paths.push(currentPath);
      }
    }
    return paths;
  }
  /**
      * Get a file from the cache
      * @param path The path of the file to get from the cache
      * @returns The file if it exists in the cache, otherwise undefined
      */
  getFile(path) {
    return this.files.find((f) => f.file.path === path);
  }
  /**
      * Checks whether a file is a sidecar file managed by the plugin
      * @param file The file to validate
      * @returns Whether or not it is a sidecar file managed by the plugin
      */
  isSidecar(file) {
    return this.isSidecarFromPath(file.path);
  }
  isSidecarFromPath(path) {
    if (!path.endsWith(Sidecar.EXTENSION)) return false;
    const mediaPath = path.substring(0, path.length - Sidecar.EXTENSION.length);
    const mediaFile = this.getFile(mediaPath);
    return mediaFile !== void 0;
  }
  /**
   * Takes every file in the cache and calls the function to hide itself from the
   * given file explorer leaf.
   * @param leaf The file manager leaf to hide things from
   */
  async hideAll(leaf) {
    for (const file of this.files) {
      file.sidecar.hide(leaf);
    }
  }
};

// src/mutationHandler.ts
var import_obsidian2 = require("obsidian");
var MutationHandler = class extends EventTarget {
  constructor(app, plugin, cache) {
    super();
    this.app = app;
    this.plugin = plugin;
    this.cache = cache;
  }
  initializeEvents() {
    this.plugin.registerEvent(this.app.vault.on("create", this.onFileCreated.bind(this)));
    this.plugin.registerEvent(this.app.vault.on("delete", this.onDeleted.bind(this)));
    this.plugin.registerEvent(this.app.vault.on("rename", this.onMoved.bind(this)));
    this.plugin.registerEvent(this.app.vault.on("modify", this.onFileEdited.bind(this)));
  }
  /**
      * Callback for file editing
      * @param file The edited file
      */
  onFileEdited(file) {
    if (!(file instanceof import_obsidian2.TFile)) return;
    const isMarkdown = file.extension === "md";
    let mediaPath = file.path;
    if (isMarkdown && !file.path.endsWith(Sidecar.EXTENSION)) return;
    if (isMarkdown) {
      mediaPath = file.path.substring(0, file.path.length - Sidecar.EXTENSION.length);
    }
    const f = this.cache.getFile(mediaPath);
    if (f) {
      void f.update();
      if (isMarkdown) {
        this.cache.sidecarUpdated(f);
        this.dispatchEvent(new CustomEvent("sidecar-edited", { detail: f }));
      } else {
        this.dispatchEvent(new CustomEvent("file-edited", { detail: f }));
      }
    }
  }
  /**
      * Callback for file deletion
      * @param file The deleted file
      */
  onDeleted(file) {
    if (!(file instanceof import_obsidian2.TFile)) return;
    const isSidecar = this.cache.isSidecar(file);
    if (isSidecar) {
      const mediaPath = file.path.substring(0, file.path.length - 11);
      const mediaFile = this.app.vault.getFileByPath(mediaPath);
      if (mediaFile) this.onFileCreated(mediaFile);
    }
    if (!this.plugin.settings.extensions.contains(file.extension.toLowerCase())) return;
    const f = this.cache.getFile(file.path);
    this.cache.removeFile(file);
    if (f) {
      this.dispatchEvent(new CustomEvent("file-deleted", { detail: f }));
    }
    const sidecar = this.app.vault.getFileByPath(`${file.path}${Sidecar.EXTENSION}`);
    if (sidecar) {
      void this.app.fileManager.trashFile(sidecar);
    }
  }
  /**
      * Callback for file moving or renaming
      * @param file The new file
      * @param oldpath The old path of the file
      */
  onMoved(file, oldpath) {
    if (!(file instanceof import_obsidian2.TFile)) return;
    const isSidecar = this.cache.isSidecarFromPath(oldpath);
    if (isSidecar) {
      const mediaPath = oldpath.substring(0, oldpath.length - Sidecar.EXTENSION.length);
      const mediaFile = this.app.vault.getFileByPath(mediaPath);
      if (mediaFile) {
        this.onFileCreated(mediaFile);
      }
    }
    if (!this.plugin.settings.extensions.contains(file.extension.toLowerCase())) return;
    const cacheFile = this.cache.getFile(file.path);
    const sidecar = this.app.vault.getFileByPath(`${oldpath}${Sidecar.EXTENSION}`);
    if (sidecar) {
      void this.app.fileManager.renameFile(sidecar, `${file.path}${Sidecar.EXTENSION}`);
    }
    if (!cacheFile) {
      this.createMediaFile(file, sidecar).then((mediaFile) => {
        if (mediaFile) {
          this.cache.fileMoved(mediaFile, oldpath);
          this.dispatchEvent(new CustomEvent("file-moved", { detail: { file: mediaFile, oldPath: oldpath } }));
        }
      });
    }
  }
  /**
      * Callback for file creation
      * @param file The created file
      */
  onFileCreated(file) {
    this.createMediaFile(file).then((mediaFile) => {
      if (mediaFile) {
        this.dispatchEvent(new CustomEvent("file-created", { detail: mediaFile }));
      }
    });
  }
  /**
   * Created a MediaFile of the correct type. E.g.; For an image, an MCImage will be made.
   * @param file The file to be made a mediaFile for. Will be checked to be of type TFile and whether its
   * extension is in the current plugin settings
   * @param sidecar The sidecar file, if there is already one. For example, if the file has been moved.
   * @returns The created media file, of the correct type, or null if none was created
   */
  async createMediaFile(file, sidecar = null) {
    if (!(file instanceof import_obsidian2.TFile) || !this.plugin.settings.extensions.contains(file.extension.toLowerCase())) return null;
    if (this.cache.getFile(file.path)) return null;
    let mediaFile = null;
    switch (getMediaType(file.extension)) {
      case "image" /* Image */:
        mediaFile = await MCImage.create(file, this.app, this.plugin, sidecar);
        break;
      case "video" /* Video */:
      case "unknown" /* Unknown */:
        mediaFile = await MediaFile.create(file, this.app, this.plugin, sidecar);
        break;
    }
    if (mediaFile) {
      this.cache.addFile(mediaFile);
    }
    return mediaFile;
  }
};

// src/views/sidecar-view.ts
var import_obsidian3 = require("obsidian");
var VIEW_TYPE_SIDECAR = "mc-sidecar";
var ILLEGAL_FILENAMES = [
  "CON",
  "PRN",
  "AUX",
  "NUL",
  "COM1",
  "COM2",
  "COM3",
  "COM4",
  "COM5",
  "COM6",
  "COM7",
  "COM8",
  "COM9",
  "LPT1",
  "LPT2",
  "LPT3",
  "LPT4",
  "LPT5",
  "LPT6",
  "LPT7",
  "LPT8",
  "LPT9",
  ".",
  ".."
];
var ILLEGAL_FILENAME_CHARACTERS = [
  "/",
  "<",
  ">",
  ":",
  '"',
  "\\",
  "|",
  "?",
  "*",
  "[",
  "]",
  "^",
  "#"
];
var SidecarView = class extends import_obsidian3.FileView {
  constructor(leaf) {
    super(leaf);
    this.editorView = null;
    this.editorObserver = null;
    this.sidecarFile = null;
    this.fileContent = "";
    this.fileContentLastEdited = 0;
    this.saveDebounce = (0, import_obsidian3.debounce)(() => this.saveFile(), 500, true);
    this.renameDebounce = (0, import_obsidian3.debounce)(() => this.renameFile(), 1e3, true);
  }
  getViewType() {
    return VIEW_TYPE_SIDECAR;
  }
  getDisplayText() {
    var _a, _b;
    return (_b = (_a = this.file) == null ? void 0 : _a.basename) != null ? _b : "Media Companion";
  }
  getIcon() {
    return "image";
  }
  canAcceptExtension(extension) {
    return getMediaType(extension) !== "unknown" /* Unknown */;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("mc-sidecar-view");
    this.mediaContainerEl = contentEl.createDiv({ cls: "mc-media-preview" });
    this.renameTitleEl = contentEl.createEl("textarea", { cls: "mc-sidecar-title" });
    this.renameTitleEl.addEventListener("input", () => this.renameDebounce());
    this.renameTitleEl.addEventListener("keydown", (e) => this.onTitleKeyDown(e));
    this.renameTitleEl.hidden = true;
    this.titleMessageEl = contentEl.createEl("p", {
      cls: "mc-sidecar-title-message",
      text: "Invalid filename"
    });
    this.titleMessageEl.hidden = true;
    this.editorContainerEl = contentEl.createDiv({ cls: "mc-sidecar-editor" });
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        var _a, _b;
        if (!(file instanceof import_obsidian3.TFile)) return;
        if (this.file && file === this.file) {
          const oldBasename = (_b = (_a = oldPath.split("/").pop()) == null ? void 0 : _a.replace(/\.[^.]+$/, "")) != null ? _b : "";
          if (this.renameTitleEl.value === oldBasename) {
            this.renameTitleEl.value = this.file.basename;
          }
          this.sidecarFile = this.app.vault.getFileByPath(
            this.file.path + Sidecar.EXTENSION
          );
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        var _a;
        if (file instanceof import_obsidian3.TFile && this.sidecarFile && file === this.sidecarFile && this.editorView) {
          if (Date.now() - this.fileContentLastEdited < 2e3) return;
          const content = await this.app.vault.read(this.sidecarFile);
          if (content !== this.editorView.data) {
            (_a = this.editorObserver) == null ? void 0 : _a.disconnect();
            this.editorView.set(content, true);
            this.fileContent = content;
            this.startEditorObserver();
          }
        }
      })
    );
    if (!this.file) {
      this.showEmptyState();
    }
  }
  async onLoadFile(file) {
    this.destroyEditor();
    this.sidecarFile = this.app.vault.getFileByPath(
      file.path + Sidecar.EXTENSION
    );
    this.renderMediaPreview(file);
    this.renameTitleEl.value = file.basename;
    this.renameTitleEl.hidden = false;
    this.titleMessageEl.hidden = true;
    this.renameTitleEl.removeClass("mc-sidecar-title-invalid");
    if (this.sidecarFile) {
      this.editorContainerEl.empty();
      this.editorView = this.app.embedRegistry.embedByExtension.md(
        { app: this.app, containerEl: this.editorContainerEl },
        this.sidecarFile,
        ""
      );
      this.editorView.editable = true;
      this.editorView.showEditor();
      this.fileContent = await this.app.vault.read(this.sidecarFile);
      this.editorView.set(this.fileContent, true);
      requestAnimationFrame(() => {
        var _a;
        if ((_a = this.editorView) == null ? void 0 : _a.inlineTitleEl) {
          this.editorView.inlineTitleEl.style.display = "none";
        }
        this.startEditorObserver();
      });
    } else {
      this.editorContainerEl.empty();
      this.editorContainerEl.createEl("p", {
        text: "No sidecar file found.",
        cls: "mc-sidecar-empty"
      });
    }
  }
  async onUnloadFile(file) {
    this.flushPendingChanges();
    this.destroyEditor();
    this.mediaContainerEl.empty();
    this.sidecarFile = null;
  }
  async onClose() {
    this.flushPendingChanges();
    this.destroyEditor();
  }
  renderMediaPreview(file) {
    this.mediaContainerEl.empty();
    const resourcePath = this.app.vault.getResourcePath(file);
    const mediaType = getMediaType(file.extension);
    if (mediaType === "image" /* Image */) {
      this.mediaContainerEl.createEl("img", {
        attr: { src: resourcePath, alt: file.basename },
        cls: "mc-media-element"
      });
    } else if (mediaType === "video" /* Video */) {
      this.mediaContainerEl.createEl("video", {
        attr: { src: resourcePath, controls: "" },
        cls: "mc-media-element"
      });
    } else {
      const embedCreator = this.app.embedRegistry.getEmbedCreator(file);
      if (embedCreator) {
        const embedEl = this.mediaContainerEl.createDiv();
        const embed = embedCreator(
          { app: this.app, containerEl: embedEl },
          file,
          file.path
        );
        if (embed.loadFile) embed.loadFile();
      } else {
        this.mediaContainerEl.createDiv({
          text: file.basename,
          cls: "mc-sidecar-empty"
        });
      }
    }
  }
  startEditorObserver() {
    if (this.editorObserver) this.editorObserver.disconnect();
    this.editorObserver = new MutationObserver(() => {
      this.saveDebounce();
    });
    this.editorObserver.observe(this.editorContainerEl, {
      childList: true,
      subtree: true,
      characterData: true
    });
  }
  destroyEditor() {
    if (this.editorObserver) {
      this.editorObserver.disconnect();
      this.editorObserver = null;
    }
    this.editorView = null;
  }
  flushPendingChanges() {
    this.saveDebounce.run();
    this.saveDebounce.cancel();
    this.renameDebounce.run();
    this.renameDebounce.cancel();
  }
  saveFile() {
    if (!this.sidecarFile || !this.editorView) return;
    const data = this.editorView.data;
    if (!data || this.fileContent === data) return;
    this.fileContent = data;
    this.fileContentLastEdited = Date.now();
    void this.app.vault.modify(this.sidecarFile, data);
  }
  renameFile() {
    var _a, _b;
    if (!this.file) return;
    const trimmed = this.renameTitleEl.value.trim();
    const parentPath = (_b = (_a = this.file.parent) == null ? void 0 : _a.path) != null ? _b : "";
    const newPath = (0, import_obsidian3.normalizePath)(
      parentPath + "/" + trimmed + "." + this.file.extension
    );
    if (trimmed === this.file.basename) {
      this.setTitleValid();
      return;
    }
    if (ILLEGAL_FILENAMES.includes(trimmed) || trimmed.length === 0 || trimmed.endsWith(".")) {
      this.setTitleInvalid();
      return;
    }
    if (this.app.vault.getAbstractFileByPathInsensitive(newPath)) {
      this.setTitleInvalid();
      return;
    }
    this.setTitleValid();
    this.app.fileManager.renameFile(this.file, newPath);
  }
  setTitleInvalid() {
    this.renameTitleEl.addClass("mc-sidecar-title-invalid");
    this.titleMessageEl.hidden = false;
  }
  setTitleValid() {
    this.renameTitleEl.removeClass("mc-sidecar-title-invalid");
    this.titleMessageEl.hidden = true;
  }
  onTitleKeyDown(e) {
    if (e.key === "Enter") {
      e.preventDefault();
      this.renameTitleEl.blur();
    }
    if (ILLEGAL_FILENAME_CHARACTERS.includes(e.key)) {
      e.preventDefault();
    }
  }
  showEmptyState() {
    this.mediaContainerEl.empty();
    this.mediaContainerEl.createEl("h3", {
      text: "No file selected",
      cls: "mc-sidecar-empty"
    });
    this.renameTitleEl.hidden = true;
  }
};

// src/views/waterfall-bases-view.ts
var import_obsidian4 = require("obsidian");

// src/model/types/shape.ts
function getShape(width, height) {
  if (width === height) {
    return "square" /* Square */;
  } else if (width > height) {
    return "horizontal" /* Horizontal */;
  } else {
    return "vertical" /* Vertical */;
  }
}

// src/util/color.ts
function rgbToHsl(r, g, b) {
  r /= 255;
  g /= 255;
  b /= 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const d = max - min;
  let h = 0;
  if (d === 0) h = 0;
  else if (max === r) h = (g - b) / d % 6;
  else if (max === g) h = (b - r) / d + 2;
  else if (max === b) h = (r - g) / d + 4;
  const l = (min + max) / 2;
  const s = d === 0 ? 0 : d / (1 - Math.abs(2 * l - 1));
  return [h * 60, s, l];
}
function hexToRgb(hex) {
  const match = hex.match(/^#([0-9a-fA-F]{2})([0-9a-fA-F]{2})([0-9a-fA-F]{2})$/);
  if (!match) return null;
  return [parseInt(match[1], 16), parseInt(match[2], 16), parseInt(match[3], 16)];
}
function isColorWithinThreshold(targetH, targetS, targetL, colors, threshold = 0.5) {
  if (!colors || !Array.isArray(colors) || colors.length === 0) return false;
  let distance2 = 0;
  for (const color of colors) {
    const ch = color.h * 360;
    const cs = color.s;
    const cl = color.l;
    const hDiff = Math.min(Math.abs(ch - targetH), 360 - Math.abs(ch - targetH));
    const sDiff = Math.abs(cs - targetS);
    const lDiff = Math.abs(cl - targetL);
    distance2 += (hDiff / 180 + sDiff + lDiff) * color.area;
    if (distance2 > threshold) return false;
  }
  return true;
}

// src/views/waterfall-bases-view.ts
var BASES_VIEW_TYPE_WATERFALL = "mc-waterfall";
var LABEL_HEIGHT = 24;
var BUFFER_PX = 800;
var PADDING = 8;
var WaterfallBasesView = class extends import_obsidian4.BasesView {
  constructor(controller, parentEl, getPluginSettings) {
    super(controller);
    this.type = BASES_VIEW_TYPE_WATERFALL;
    this.hoverPopover = null;
    this.layoutItems = [];
    this.columnHeights = [];
    this.numColumns = 1;
    this.colWidthSetting = 200;
    this.gap = 8;
    this.showFilename = true;
    this.showProperties = false;
    this.actualColWidth = 200;
    this.offsetX = 0;
    this.rafId = null;
    this.hoverTimer = null;
    this.fullscreenOverlay = null;
    this.fullscreenItem = null;
    this.settingsChangedRef = null;
    this.lastDataFingerprint = "";
    this.lastShowFilename = true;
    this.lastShowProperties = false;
    this.visibleProperties = [];
    this.lastPropsFingerprint = "";
    this.getPluginSettings = getPluginSettings;
    this.scrollEl = parentEl.createDiv({ cls: "mc-waterfall-scroll" });
    this.containerEl = this.scrollEl.createDiv({ cls: "mc-waterfall-container" });
    this.scrollEl.addEventListener("scroll", () => this.scheduleSync(), { passive: true });
    this.resizeObserver = new ResizeObserver(() => {
      this.relayoutInPlace();
    });
    this.resizeObserver.observe(this.scrollEl);
    this.settingsChangedRef = () => this.refreshVisibleItems();
    this.app.workspace.on("mc:settings-changed", this.settingsChangedRef);
  }
  scheduleSync() {
    if (this.rafId !== null) return;
    this.rafId = requestAnimationFrame(() => {
      this.rafId = null;
      this.syncDOM();
    });
  }
  onDataUpdated() {
    const newColWidth = Number(this.config.get("columnWidth")) || 200;
    const newGap = Number(this.config.get("gap")) || 8;
    const newShowFilename = this.config.get("showFilename") !== false;
    const newShowProperties = this.config.get("showProperties") === true;
    const newVisibleProperties = this.config.getOrder().filter((pid) => {
      const parsed = (0, import_obsidian4.parsePropertyId)(pid);
      return !(parsed.type === "file" && parsed.name === "fileName");
    });
    const newPropsFingerprint = newVisibleProperties.join(",");
    this.visibleProperties = newVisibleProperties;
    const filterColor = String(this.config.get("filterColor") || "").trim();
    const colorThreshold = Number(this.config.get("colorThreshold")) || 50;
    const filterShape = String(this.config.get("filterShape") || "").trim().toLowerCase();
    const filterMinWidth = parseInt(String(this.config.get("filterMinWidth") || ""), 10) || 0;
    const filterMaxWidth = parseInt(String(this.config.get("filterMaxWidth") || ""), 10) || 0;
    const filterMinHeight = parseInt(String(this.config.get("filterMinHeight") || ""), 10) || 0;
    const filterMaxHeight = parseInt(String(this.config.get("filterMaxHeight") || ""), 10) || 0;
    const searchQuery = String(this.config.get("searchQuery") || "").trim().toLowerCase();
    const dataIds = this.data.groupedData.flatMap((g) => g.entries.map((e) => e.file.path)).join("\n");
    const fingerprint = `${dataIds}|${filterColor}|${colorThreshold}|${filterShape}|${filterMinWidth}|${filterMaxWidth}|${filterMinHeight}|${filterMaxHeight}|${searchQuery}`;
    const layoutOnly = fingerprint === this.lastDataFingerprint && this.layoutItems.length > 0;
    this.colWidthSetting = newColWidth;
    this.gap = newGap;
    this.showFilename = newShowFilename;
    this.showProperties = newShowProperties;
    if (layoutOnly) {
      if (newShowFilename !== this.lastShowFilename) {
        const delta = newShowFilename ? LABEL_HEIGHT : -LABEL_HEIGHT;
        for (const item of this.layoutItems) {
          item.itemHeight += delta;
        }
        for (const item of this.layoutItems) {
          if (!item.el) continue;
          const existing = item.el.querySelector(".mc-waterfall-name");
          if (newShowFilename && !existing) {
            const propsEl = item.el.querySelector(".mc-waterfall-props");
            const nameEl = createDiv({ cls: "mc-waterfall-name", text: item.mediaFile.basename });
            if (propsEl) {
              item.el.insertBefore(nameEl, propsEl);
            } else {
              item.el.appendChild(nameEl);
            }
          } else if (!newShowFilename && existing) {
            existing.remove();
          }
        }
      }
      this.lastShowFilename = newShowFilename;
      const propsToggled = newShowProperties !== this.lastShowProperties;
      const propsListChanged = newPropsFingerprint !== this.lastPropsFingerprint;
      if (propsToggled || newShowProperties && propsListChanged) {
        for (const item of this.layoutItems) {
          if (item.propsHeight > 0) {
            item.itemHeight -= item.propsHeight;
          }
          item.propsMeasured = false;
          item.propsHeight = 0;
          if (!item.el) continue;
          const existing = item.el.querySelector(".mc-waterfall-props");
          if (existing) existing.remove();
          if (newShowProperties && this.visibleProperties.length > 0) {
            if (item.entry) this.renderProperties(item.el, item.entry);
          }
        }
        this.relayoutInPlace(true, true);
        if (newShowProperties && this.visibleProperties.length > 0) {
          this.measureMountedProps();
        }
      } else {
        this.relayoutInPlace(true, true);
      }
      this.lastShowProperties = newShowProperties;
      this.lastPropsFingerprint = newPropsFingerprint;
      return;
    }
    this.lastDataFingerprint = fingerprint;
    this.lastShowFilename = newShowFilename;
    this.lastShowProperties = newShowProperties;
    this.lastPropsFingerprint = newPropsFingerprint;
    let targetHsl = null;
    if (filterColor) {
      const rgb = hexToRgb(filterColor);
      if (rgb) targetHsl = rgbToHsl(rgb[0], rgb[1], rgb[2]);
    }
    this.clearDOM();
    this.layoutItems = [];
    const seenMediaPaths = /* @__PURE__ */ new Set();
    const itemByMediaPath = /* @__PURE__ */ new Map();
    const foldersInResult = /* @__PURE__ */ new Set();
    let deduplicatedCount = 0;
    for (const group of this.data.groupedData) {
      for (const entry of group.entries) {
        const resolved = this.resolveMediaFile(entry.file);
        if (!resolved) continue;
        const { mediaFile, sidecarFile } = resolved;
        if (mediaFile.parent) foldersInResult.add(mediaFile.parent.path);
        if (seenMediaPaths.has(mediaFile.path)) {
          if (entry.file.path.endsWith(Sidecar.EXTENSION)) {
            const existing = itemByMediaPath.get(mediaFile.path);
            if (existing) {
              existing.sidecarFile = sidecarFile;
              existing.entry = entry;
            }
          }
          deduplicatedCount++;
          continue;
        }
        seenMediaPaths.add(mediaFile.path);
        const meta = this.readSidecarMeta(sidecarFile);
        if (searchQuery && !mediaFile.path.toLowerCase().includes(searchQuery)) continue;
        if (filterShape && meta.width > 0 && meta.height > 0 && getShape(meta.width, meta.height) !== filterShape) continue;
        if (filterMinWidth > 0 && meta.width > 0 && meta.width < filterMinWidth) continue;
        if (filterMaxWidth > 0 && meta.width > 0 && meta.width > filterMaxWidth) continue;
        if (filterMinHeight > 0 && meta.height > 0 && meta.height < filterMinHeight) continue;
        if (filterMaxHeight > 0 && meta.height > 0 && meta.height > filterMaxHeight) continue;
        if (targetHsl && meta.colors) {
          if (!isColorWithinThreshold(targetHsl[0], targetHsl[1], targetHsl[2], meta.colors, colorThreshold / 100)) continue;
        }
        const item = {
          mediaFile,
          sidecarFile,
          entry,
          metaWidth: meta.width,
          metaHeight: meta.height,
          colors: meta.colors,
          col: 0,
          x: 0,
          y: 0,
          itemHeight: 0,
          measured: false,
          propsMeasured: false,
          propsHeight: 0,
          el: null
        };
        this.layoutItems.push(item);
        itemByMediaPath.set(mediaFile.path, item);
      }
    }
    if (deduplicatedCount > 0) {
      let remaining = deduplicatedCount;
      for (const folderPath of foldersInResult) {
        if (remaining <= 0) break;
        const folder = this.app.vault.getAbstractFileByPath(folderPath);
        if (!(folder instanceof import_obsidian4.TFolder)) continue;
        for (const child of folder.children) {
          if (remaining <= 0) break;
          if (!child.path.endsWith(Sidecar.EXTENSION)) continue;
          const mediaPath = child.path.slice(0, -Sidecar.EXTENSION.length);
          if (seenMediaPaths.has(mediaPath)) continue;
          const sidecarFile = this.app.vault.getFileByPath(child.path);
          if (!sidecarFile) continue;
          const mediaFile = this.app.vault.getFileByPath(mediaPath);
          if (!mediaFile) continue;
          seenMediaPaths.add(mediaPath);
          const meta = this.readSidecarMeta(sidecarFile);
          if (searchQuery && !mediaFile.path.toLowerCase().includes(searchQuery)) continue;
          if (filterShape && meta.width > 0 && meta.height > 0 && getShape(meta.width, meta.height) !== filterShape) continue;
          if (filterMinWidth > 0 && meta.width > 0 && meta.width < filterMinWidth) continue;
          if (filterMaxWidth > 0 && meta.width > 0 && meta.width > filterMaxWidth) continue;
          if (filterMinHeight > 0 && meta.height > 0 && meta.height < filterMinHeight) continue;
          if (filterMaxHeight > 0 && meta.height > 0 && meta.height > filterMaxHeight) continue;
          if (targetHsl && meta.colors) {
            if (!isColorWithinThreshold(targetHsl[0], targetHsl[1], targetHsl[2], meta.colors, colorThreshold / 100)) continue;
          }
          this.layoutItems.push({
            mediaFile,
            sidecarFile,
            entry: null,
            metaWidth: meta.width,
            metaHeight: meta.height,
            colors: meta.colors,
            col: 0,
            x: 0,
            y: 0,
            itemHeight: 0,
            measured: false,
            propsMeasured: false,
            propsHeight: 0,
            el: null
          });
          remaining--;
        }
      }
    }
    if (this.layoutItems.length === 0) {
      this.containerEl.style.height = "";
      this.containerEl.createDiv({
        cls: "mc-waterfall-empty",
        text: "No media files found. Make sure your Base queries sidecar (.sidecar.md) files or supported media files."
      });
      return;
    }
    this.computePositions();
    this.syncDOM();
  }
  get footerHeight() {
    let h = 0;
    if (this.showFilename) h += LABEL_HEIGHT;
    return h;
  }
  computePositions() {
    const clientW = this.scrollEl.clientWidth || 400;
    const available = clientW - PADDING * 2;
    this.numColumns = Math.max(1, Math.floor((available + this.gap) / (this.colWidthSetting + this.gap)));
    this.actualColWidth = (available - (this.numColumns - 1) * this.gap) / this.numColumns;
    const totalUsed = this.numColumns * this.actualColWidth + (this.numColumns - 1) * this.gap;
    this.offsetX = (clientW - totalUsed) / 2;
    this.columnHeights = new Array(this.numColumns).fill(PADDING);
    for (const item of this.layoutItems) {
      const col = this.shortestColumn();
      item.col = col;
      item.x = this.offsetX + col * (this.actualColWidth + this.gap);
      item.y = this.columnHeights[col];
      if (!item.measured) {
        const mediaH = item.metaWidth > 0 && item.metaHeight > 0 ? this.actualColWidth / item.metaWidth * item.metaHeight : this.actualColWidth;
        item.itemHeight = mediaH + this.footerHeight + item.propsHeight;
      }
      this.columnHeights[col] += item.itemHeight + this.gap;
    }
    this.containerEl.style.height = `${Math.max(0, ...this.columnHeights)}px`;
  }
  shortestColumn() {
    let min = 0;
    for (let i = 1; i < this.numColumns; i++) {
      if (this.columnHeights[i] < this.columnHeights[min]) min = i;
    }
    return min;
  }
  relayoutInPlace(force = false, animate = false) {
    if (this.layoutItems.length === 0) return;
    const oldColWidth = this.actualColWidth;
    const available = (this.scrollEl.clientWidth || 400) - PADDING * 2;
    const newNumCols = Math.max(1, Math.floor((available + this.gap) / (this.colWidthSetting + this.gap)));
    const newColWidth = (available - (newNumCols - 1) * this.gap) / newNumCols;
    if (!force && newNumCols === this.numColumns && Math.abs(newColWidth - oldColWidth) < 0.5) return;
    if (!animate) {
      this.containerEl.classList.add("mc-no-transition");
    }
    const scale = newColWidth / (oldColWidth || 1);
    for (const item of this.layoutItems) {
      if (item.measured) {
        const footer = this.footerHeight + item.propsHeight;
        item.itemHeight = (item.itemHeight - footer) * scale + footer;
      }
    }
    this.computePositions();
    for (const item of this.layoutItems) {
      if (!item.el) continue;
      item.el.style.top = `${item.y}px`;
      item.el.style.left = `${item.x}px`;
      item.el.style.width = `${this.actualColWidth}px`;
      item.el.style.height = `${item.itemHeight}px`;
    }
    this.syncDOM();
    if (!animate) {
      requestAnimationFrame(() => {
        this.containerEl.classList.remove("mc-no-transition");
      });
    }
  }
  reflowColumn(changed, newHeight) {
    const delta = newHeight - changed.itemHeight;
    if (Math.abs(delta) < 1) return;
    changed.itemHeight = newHeight;
    if (changed.el) changed.el.style.height = `${newHeight}px`;
    const col = changed.col;
    let past = false;
    for (const item of this.layoutItems) {
      if (item === changed) {
        past = true;
        continue;
      }
      if (!past || item.col !== col) continue;
      item.y += delta;
      if (item.el) item.el.style.top = `${item.y}px`;
    }
    this.columnHeights[col] += delta;
    this.containerEl.style.height = `${Math.max(0, ...this.columnHeights)}px`;
    this.syncDOM();
  }
  /**
   * Measure the rendered props height of all mounted items that haven't
   * been measured yet, and grow them to fit.  Used after toggling props on
   * so the layout adjusts to the new content.
   */
  measureMountedProps() {
    requestAnimationFrame(() => {
      for (const item of this.layoutItems) {
        if (item.propsMeasured || !item.el) continue;
        const propsEl = item.el.querySelector(".mc-waterfall-props");
        const propsH = propsEl ? propsEl.offsetHeight : 0;
        item.propsMeasured = true;
        item.propsHeight = propsH;
        if (propsH > 0) {
          const newH = item.itemHeight + propsH;
          item.el.style.height = `${newH}px`;
          this.reflowColumn(item, newH);
        }
      }
    });
  }
  syncDOM() {
    const scrollTop = this.scrollEl.scrollTop;
    const viewHeight = this.scrollEl.clientHeight;
    const top = scrollTop - BUFFER_PX;
    const bottom = scrollTop + viewHeight + BUFFER_PX;
    for (const item of this.layoutItems) {
      const inView = item.y + item.itemHeight > top && item.y < bottom;
      if (inView && !item.el) {
        this.mountItem(item);
      } else if (!inView && item.el) {
        item.el.remove();
        item.el = null;
      }
    }
  }
  clearDOM() {
    for (const item of this.layoutItems) {
      if (item.el) {
        item.el.remove();
        item.el = null;
      }
    }
    this.containerEl.empty();
  }
  mountItem(item) {
    const el = this.containerEl.createDiv({ cls: "mc-waterfall-item" });
    item.el = el;
    el.style.top = `${item.y}px`;
    el.style.left = `${item.x}px`;
    el.style.width = `${this.actualColWidth}px`;
    el.style.height = `${item.itemHeight}px`;
    const mc = el.createDiv({ cls: "mc-waterfall-media" });
    const mediaH = item.itemHeight - this.footerHeight;
    const ph = mc.createDiv({ cls: "mc-waterfall-placeholder" });
    ph.style.height = `${Math.max(mediaH, 50)}px`;
    this.loadMediaContent(item, el, mc);
    const { fullscreenMode: fsMode, fullscreenHoverDelay: fsDelay } = this.getPluginSettings();
    if (fsMode !== "off") {
      const btn = mc.createDiv({ cls: "mc-waterfall-fullscreen-btn" });
      btn.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" x2="16.65" y1="21" y2="16.65"/><line x1="11" x2="11" y1="8" y2="14"/><line x1="8" x2="14" y1="11" y2="11"/></svg>';
      if (fsMode === "hover") {
        btn.addEventListener("mouseenter", () => {
          this.clearHoverTimer();
          this.hoverTimer = setTimeout(() => {
            this.showFullscreen(item);
          }, fsDelay);
        });
        btn.addEventListener("mouseleave", () => {
          this.clearHoverTimer();
        });
      }
      btn.addEventListener("click", (evt) => {
        evt.stopPropagation();
        this.showFullscreen(item);
      });
    }
    if (this.showFilename) {
      el.createDiv({ cls: "mc-waterfall-name", text: item.mediaFile.basename });
    }
    if (this.showProperties && this.visibleProperties.length > 0) {
      if (item.entry) this.renderProperties(el, item.entry);
    }
    if (!item.propsMeasured && this.showProperties && this.visibleProperties.length > 0) {
      el.style.overflow = "visible";
      requestAnimationFrame(() => {
        if (!item.el || item.propsMeasured) return;
        const propsEl = item.el.querySelector(".mc-waterfall-props");
        const propsH = propsEl ? propsEl.offsetHeight : 0;
        item.propsMeasured = true;
        item.propsHeight = propsH;
        item.el.style.overflow = "";
        if (propsH > 0) {
          const newH = item.itemHeight + propsH;
          item.el.style.height = `${newH}px`;
          this.reflowColumn(item, newH);
        }
      });
    }
    el.setAttribute("draggable", "true");
    el.addEventListener("dragstart", (evt) => {
      if (!evt.dataTransfer) return;
      const resourcePath = this.app.vault.getResourcePath(item.mediaFile);
      evt.dataTransfer.setData("text/uri-list", resourcePath);
      evt.dataTransfer.setData("text/plain", item.mediaFile.path);
      evt.dataTransfer.effectAllowed = "copy";
      const img = el.querySelector("img");
      if (img) evt.dataTransfer.setDragImage(img, 0, 0);
    });
    el.addEventListener("contextmenu", (evt) => {
      evt.preventDefault();
      const menu = new import_obsidian4.Menu();
      menu.addItem(
        (mi) => mi.setTitle("Copy").setIcon("copy").onClick(() => void this.copyMediaToClipboard(item.mediaFile))
      );
      menu.addItem(
        (mi) => mi.setTitle("Delete").setIcon("trash").onClick(() => void this.deleteMediaFile(item))
      );
      menu.showAtMouseEvent(evt);
    });
    el.addEventListener("click", (evt) => {
      if (evt.button !== 0 && evt.button !== 1) return;
      evt.preventDefault();
      if (import_obsidian4.Keymap.isModEvent(evt)) {
        const newLeaf = this.app.workspace.getLeaf("tab");
        void newLeaf.setViewState({
          type: VIEW_TYPE_SIDECAR,
          state: { file: item.mediaFile.path }
        });
        this.app.workspace.setActiveLeaf(newLeaf, { focus: true });
      } else {
        void this.openInSidebar(item.mediaFile);
      }
    });
    el.addEventListener("mouseover", (evt) => {
      this.app.workspace.trigger("hover-link", {
        event: evt,
        source: "mc-waterfall",
        hoverParent: this,
        targetEl: el,
        linktext: item.mediaFile.path
      });
    });
  }
  loadMediaContent(item, el, mc) {
    const resourcePath = this.app.vault.getResourcePath(item.mediaFile);
    const mediaType = getMediaType(item.mediaFile.extension);
    const onSized = (naturalW, naturalH) => {
      var _a;
      const ph = mc.querySelector(".mc-waterfall-placeholder");
      if (ph) ph.remove();
      if (item.measured) return;
      item.measured = true;
      const mediaH = naturalH * (this.actualColWidth / naturalW);
      let newH = mediaH + this.footerHeight;
      if (item.propsMeasured) {
        const propsEl = (_a = item.el) == null ? void 0 : _a.querySelector(".mc-waterfall-props");
        if (propsEl) newH += propsEl.offsetHeight;
      }
      this.reflowColumn(item, newH);
    };
    if (mediaType === "image" /* Image */) {
      const img = mc.createEl("img", {
        attr: { src: resourcePath, alt: item.mediaFile.basename }
      });
      img.addEventListener("load", () => onSized(img.naturalWidth, img.naturalHeight));
    } else if (mediaType === "video" /* Video */) {
      const video = mc.createEl("video", {
        attr: { src: resourcePath, preload: "metadata", muted: "" }
      });
      video.addEventListener("mouseenter", () => {
        video.play().catch(() => {
        });
      });
      video.addEventListener("mouseleave", () => {
        video.pause();
        video.currentTime = 0;
      });
      video.addEventListener("loadedmetadata", () => onSized(video.videoWidth, video.videoHeight));
    } else {
      const embedCreator = this.app.embedRegistry.getEmbedCreator(item.mediaFile);
      if (embedCreator) {
        const embedEl = mc.createDiv();
        const embed = embedCreator({ app: this.app, containerEl: embedEl }, item.mediaFile, item.mediaFile.path);
        if (embed.loadFile) embed.loadFile();
      } else {
        mc.createDiv({ text: item.mediaFile.basename, cls: "mc-waterfall-name" });
      }
      item.measured = true;
      const ph = mc.querySelector(".mc-waterfall-placeholder");
      if (ph) ph.remove();
    }
  }
  resolveMediaFile(file) {
    if (file.path.endsWith(Sidecar.EXTENSION)) {
      const mediaPath = file.path.slice(0, -Sidecar.EXTENSION.length);
      const mediaFile = this.app.vault.getFileByPath(mediaPath);
      return mediaFile ? { mediaFile, sidecarFile: file } : null;
    }
    const mediaType = getMediaType(file.extension);
    if (mediaType !== "unknown" /* Unknown */) {
      const sidecarFile = this.app.vault.getFileByPath(`${file.path}${Sidecar.EXTENSION}`);
      return { mediaFile: file, sidecarFile };
    }
    return null;
  }
  readSidecarMeta(sidecarFile) {
    if (!sidecarFile) return { width: 0, height: 0, colors: null };
    const cache = this.app.metadataCache.getFileCache(sidecarFile);
    const fm = cache == null ? void 0 : cache.frontmatter;
    if (!fm) return { width: 0, height: 0, colors: null };
    let width = 0, height = 0;
    const size = fm["MC-size"];
    if (Array.isArray(size) && size.length === 2) {
      width = Number(size[0]) || 0;
      height = Number(size[1]) || 0;
    }
    let colors = null;
    const raw = fm["MC-colors"];
    if (Array.isArray(raw)) colors = raw;
    return { width, height, colors };
  }
  renderProperties(parentEl, entry) {
    const propsEl = parentEl.createDiv({ cls: "mc-waterfall-props" });
    for (const pid of this.visibleProperties) {
      const val = entry.getValue(pid);
      const name = this.config.getDisplayName(pid);
      const propEl = propsEl.createDiv({ cls: "mc-waterfall-prop" });
      const nameSpan = propEl.createSpan({ cls: "mc-waterfall-prop-name" });
      nameSpan.textContent = `${name}: `;
      const valueSpan = propEl.createSpan({ cls: "mc-waterfall-prop-value" });
      this.renderPropertyValue(valueSpan, val);
    }
  }
  renderPropertyValue(container, val) {
    var _a, _b, _c;
    if (val == null || val === "null" || val === "undefined") {
      container.appendText("-");
      return;
    }
    if (Array.isArray(val)) {
      if (val.length === 0) {
        container.appendText("-");
        return;
      }
      for (let i = 0; i < val.length; i++) {
        if (i > 0) container.appendText(", ");
        this.renderPropertyValue(container, val[i]);
      }
      return;
    }
    if (typeof val === "object" && val !== null && "path" in val) {
      const linkObj = val;
      const a = container.createEl("a", {
        cls: "mc-prop-link",
        text: linkObj.display || ((_a = linkObj.path.split("/").pop()) == null ? void 0 : _a.replace(/\.[^.]+$/, "")) || linkObj.path
      });
      a.addEventListener("click", (evt) => {
        evt.preventDefault();
        evt.stopPropagation();
        this.app.workspace.openLinkText(linkObj.path, "", import_obsidian4.Keymap.isModEvent(evt));
      });
      return;
    }
    const text = String(val);
    if (text === "" || text === "null" || text === "undefined") {
      container.appendText("-");
      return;
    }
    const wikiLinkRegex = /\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g;
    if (wikiLinkRegex.test(text)) {
      wikiLinkRegex.lastIndex = 0;
      let lastIndex = 0;
      let match;
      while ((match = wikiLinkRegex.exec(text)) !== null) {
        if (match.index > lastIndex) {
          container.appendText(text.slice(lastIndex, match.index));
        }
        const linkPath = match[1].trim();
        const display = ((_b = match[2]) == null ? void 0 : _b.trim()) || ((_c = linkPath.split("/").pop()) == null ? void 0 : _c.replace(/\.[^.]+$/, "")) || linkPath;
        const a = container.createEl("a", { cls: "mc-prop-link", text: display });
        a.addEventListener("click", (evt) => {
          evt.preventDefault();
          evt.stopPropagation();
          this.app.workspace.openLinkText(linkPath, "", import_obsidian4.Keymap.isModEvent(evt));
        });
        lastIndex = match.index + match[0].length;
      }
      if (lastIndex < text.length) {
        container.appendText(text.slice(lastIndex));
      }
      return;
    }
    const tagRegex = /#[^\s#,]+/g;
    if (tagRegex.test(text)) {
      tagRegex.lastIndex = 0;
      let lastIndex = 0;
      let match;
      while ((match = tagRegex.exec(text)) !== null) {
        if (match.index > lastIndex) {
          container.appendText(text.slice(lastIndex, match.index));
        }
        const tagText = match[0];
        const tag = container.createSpan({ cls: "mc-prop-tag", text: tagText });
        tag.addEventListener("click", (evt) => {
          var _a2, _b2, _c2, _d, _e;
          evt.preventDefault();
          evt.stopPropagation();
          (_e = (_d = (_c2 = (_b2 = (_a2 = this.app.internalPlugins) == null ? void 0 : _a2.getPluginById) == null ? void 0 : _b2.call(_a2, "global-search")) == null ? void 0 : _c2.instance) == null ? void 0 : _d.openGlobalSearch) == null ? void 0 : _e.call(_d, `tag:${tagText}`);
        });
        lastIndex = match.index + match[0].length;
      }
      if (lastIndex < text.length) {
        container.appendText(text.slice(lastIndex));
      }
      return;
    }
    if (text.startsWith("http://") || text.startsWith("https://")) {
      const a = container.createEl("a", { cls: "mc-prop-link", text });
      a.addEventListener("click", (evt) => {
        evt.preventDefault();
        evt.stopPropagation();
        window.open(text, "_blank");
      });
      return;
    }
    container.appendText(text);
  }
  async copyMediaToClipboard(mediaFile) {
    try {
      const data = await this.app.vault.readBinary(mediaFile);
      const srcMime = this.getMimeType(mediaFile.extension);
      let pngBlob;
      if (srcMime === "image/png") {
        pngBlob = new Blob([data], { type: "image/png" });
      } else if (srcMime.startsWith("image/")) {
        pngBlob = await this.convertToPng(data, srcMime);
      } else {
        await navigator.clipboard.writeText(mediaFile.path);
        new import_obsidian4.Notice(`Copied path of ${mediaFile.basename} to clipboard`);
        return;
      }
      await navigator.clipboard.write([
        new ClipboardItem({ "image/png": pngBlob })
      ]);
      new import_obsidian4.Notice(`Copied ${mediaFile.basename} to clipboard`);
    } catch (e) {
      console.error("Failed to copy media to clipboard", e);
      new import_obsidian4.Notice("Failed to copy media to clipboard");
    }
  }
  convertToPng(data, mimeType) {
    return new Promise((resolve, reject) => {
      const blob = new Blob([data], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement("canvas");
        canvas.width = img.naturalWidth;
        canvas.height = img.naturalHeight;
        const ctx = canvas.getContext("2d");
        if (!ctx) {
          URL.revokeObjectURL(url);
          reject(new Error("Canvas 2D context unavailable"));
          return;
        }
        ctx.drawImage(img, 0, 0);
        canvas.toBlob((pngBlob) => {
          URL.revokeObjectURL(url);
          if (pngBlob) resolve(pngBlob);
          else reject(new Error("Canvas toBlob returned null"));
        }, "image/png");
      };
      img.onerror = () => {
        URL.revokeObjectURL(url);
        reject(new Error("Failed to load image for conversion"));
      };
      img.src = url;
    });
  }
  async deleteMediaFile(item) {
    try {
      if (item.sidecarFile) {
        await this.app.fileManager.trashFile(item.sidecarFile);
      }
      await this.app.fileManager.trashFile(item.mediaFile);
      if (item.el) {
        item.el.remove();
        item.el = null;
      }
      this.layoutItems = this.layoutItems.filter((i) => i !== item);
      this.computePositions();
      this.syncDOM();
    } catch (e) {
      console.error("Failed to delete media file", e);
      new import_obsidian4.Notice("Failed to delete file");
    }
  }
  getMimeType(ext) {
    const map = {
      png: "image/png",
      jpg: "image/jpeg",
      jpeg: "image/jpeg",
      gif: "image/gif",
      webp: "image/webp",
      svg: "image/svg+xml",
      bmp: "image/bmp",
      mp4: "video/mp4",
      webm: "video/webm",
      ogv: "video/ogg"
    };
    return map[ext.toLowerCase()] || "application/octet-stream";
  }
  clearHoverTimer() {
    if (this.hoverTimer !== null) {
      clearTimeout(this.hoverTimer);
      this.hoverTimer = null;
    }
  }
  showFullscreen(item) {
    if (this.fullscreenOverlay) this.dismissFullscreen();
    const overlay = document.body.createDiv({ cls: "mc-waterfall-fullscreen" });
    this.fullscreenOverlay = overlay;
    this.fullscreenItem = item;
    const resourcePath = this.app.vault.getResourcePath(item.mediaFile);
    const mediaType = getMediaType(item.mediaFile.extension);
    if (mediaType === "video" /* Video */) {
      const video = overlay.createEl("video", {
        cls: "mc-waterfall-fullscreen-media",
        attr: { src: resourcePath, autoplay: "", controls: "", muted: "" }
      });
      video.play().catch(() => {
      });
    } else {
      overlay.createEl("img", {
        cls: "mc-waterfall-fullscreen-media",
        attr: { src: resourcePath, alt: item.mediaFile.basename }
      });
    }
    if (this.showFilename) {
      overlay.createDiv({ cls: "mc-waterfall-fullscreen-label", text: item.mediaFile.basename });
    }
    overlay.addEventListener("click", () => this.dismissFullscreen());
    overlay.addEventListener("mouseleave", () => this.dismissFullscreen());
    const onKey = (e) => {
      if (e.key === "Escape") this.dismissFullscreen();
    };
    document.addEventListener("keydown", onKey, { once: true });
  }
  dismissFullscreen() {
    if (this.fullscreenOverlay) {
      this.fullscreenOverlay.remove();
      this.fullscreenOverlay = null;
      this.fullscreenItem = null;
    }
  }
  async openInSidebar(mediaFile) {
    const { workspace } = this.app;
    let leaf = null;
    for (const l of workspace.getLeavesOfType(VIEW_TYPE_SIDECAR)) {
      if (l.getRoot() === workspace.rightSplit) {
        leaf = l;
        break;
      }
    }
    if (!leaf) {
      leaf = workspace.getRightLeaf(false);
      if (!leaf) return;
    }
    await leaf.setViewState({
      type: VIEW_TYPE_SIDECAR,
      state: { file: mediaFile.path }
    });
    workspace.revealLeaf(leaf);
  }
  /**
   * Unmount and re-mount all currently visible items so they pick up
   * the latest plugin settings (e.g. fullscreen mode changes).
   */
  refreshVisibleItems() {
    for (const item of this.layoutItems) {
      if (item.el) {
        item.el.remove();
        item.el = null;
      }
    }
    this.syncDOM();
  }
  onunload() {
    if (this.rafId !== null) cancelAnimationFrame(this.rafId);
    this.clearHoverTimer();
    this.dismissFullscreen();
    this.resizeObserver.disconnect();
    if (this.settingsChangedRef) {
      this.app.workspace.off("mc:settings-changed", this.settingsChangedRef);
    }
    this.clearDOM();
  }
};
function getWaterfallViewOptions() {
  return [
    {
      type: "group",
      displayName: "Layout",
      items: [
        {
          type: "slider",
          key: "columnWidth",
          displayName: "Column width",
          default: 200,
          min: 80,
          max: 600,
          step: 10,
          instant: true
        },
        {
          type: "slider",
          key: "gap",
          displayName: "Gap",
          default: 8,
          min: 0,
          max: 24,
          step: 2,
          instant: true
        },
        {
          type: "toggle",
          key: "showFilename",
          displayName: "Show filename",
          default: true
        },
        {
          type: "toggle",
          key: "showProperties",
          displayName: "Show properties",
          default: false
        }
      ]
    },
    {
      type: "group",
      displayName: "Search",
      items: [
        {
          type: "text",
          key: "searchQuery",
          displayName: "Search",
          default: "",
          placeholder: "Filter by name or path\u2026",
          instant: true
        }
      ]
    },
    {
      type: "group",
      displayName: "Media Filters",
      items: [
        {
          type: "dropdown",
          key: "filterShape",
          displayName: "Shape",
          default: "",
          options: {
            "": "Any",
            "square": "Square",
            "horizontal": "Horizontal",
            "vertical": "Vertical"
          }
        },
        {
          type: "text",
          key: "filterColor",
          displayName: "Colour (hex)",
          default: "",
          placeholder: "#ff0000"
        },
        {
          type: "slider",
          key: "colorThreshold",
          displayName: "Colour proximity (%)",
          default: 50,
          min: 1,
          max: 100,
          step: 1
        },
        {
          type: "text",
          key: "filterMinWidth",
          displayName: "Min width (px)",
          default: "",
          placeholder: "0"
        },
        {
          type: "text",
          key: "filterMaxWidth",
          displayName: "Max width (px)",
          default: "",
          placeholder: "0"
        },
        {
          type: "text",
          key: "filterMinHeight",
          displayName: "Min height (px)",
          default: "",
          placeholder: "0"
        },
        {
          type: "text",
          key: "filterMaxHeight",
          displayName: "Max height (px)",
          default: "",
          placeholder: "0"
        }
      ]
    }
  ];
}

// src/api/server.ts
var import_obsidian5 = require("obsidian");
var ApiServer = class {
  constructor(app, plugin, cache) {
    this.server = null;
    this.app = app;
    this.plugin = plugin;
    this.cache = cache;
  }
  /**
   * Start the API server. Only works on desktop platforms.
   */
  start() {
    if (!import_obsidian5.Platform.isDesktopApp) {
      console.debug("[Media Companion API] Skipping server start on mobile");
      return;
    }
    if (!this.plugin.settings.apiEnabled) return;
    if (this.server) return;
    try {
      const http = require("http");
      this.server = http.createServer(async (req, res) => {
        try {
          await this.handleRequest(req, res);
        } catch (e) {
          console.error("[Media Companion API] Unhandled request error:", e);
          this.sendJson(res, 500, { error: "Internal server error" });
        }
      });
      this.server.listen(this.plugin.settings.apiPort, "127.0.0.1", () => {
        console.log(
          `[Media Companion API] Listening on http://127.0.0.1:${this.plugin.settings.apiPort}`
        );
        new import_obsidian5.Notice(
          `Media Companion API started on port ${this.plugin.settings.apiPort}`
        );
      });
      this.server.on("error", (err) => {
        if (err.code === "EADDRINUSE") {
          console.error(
            `[Media Companion API] Port ${this.plugin.settings.apiPort} already in use`
          );
          new import_obsidian5.Notice(
            `Media Companion API: Port ${this.plugin.settings.apiPort} is already in use`
          );
        } else {
          console.error("[Media Companion API] Server error:", err);
          new import_obsidian5.Notice(`Media Companion API error: ${err.message}`);
        }
        this.server = null;
      });
    } catch (e) {
      console.error("[Media Companion API] Failed to start:", e);
    }
  }
  stop() {
    if (this.server) {
      this.server.close();
      this.server = null;
    }
  }
  restart() {
    this.stop();
    this.start();
  }
  async handleRequest(req, res) {
    var _a, _b;
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
    res.setHeader(
      "Access-Control-Allow-Headers",
      "Content-Type, Authorization"
    );
    if (req.method === "OPTIONS") {
      res.writeHead(204);
      res.end();
      return;
    }
    if (this.plugin.settings.apiKey) {
      const auth = (_a = req.headers["authorization"]) != null ? _a : "";
      if (auth !== `Bearer ${this.plugin.settings.apiKey}`) {
        this.sendJson(res, 401, { error: "Unauthorized" });
        return;
      }
    }
    const url = new URL(
      (_b = req.url) != null ? _b : "/",
      `http://127.0.0.1:${this.plugin.settings.apiPort}`
    );
    const pathname = url.pathname;
    if (pathname === "/api/ping" && req.method === "GET") {
      this.handlePing(res);
    } else if (pathname === "/api/folders" && req.method === "GET") {
      this.handleFolders(res);
    } else if (pathname === "/api/tags" && req.method === "GET") {
      this.handleTags(res);
    } else if (pathname === "/api/upload" && req.method === "POST") {
      const body = await this.readBody(req);
      await this.handleUpload(body, res);
    } else {
      this.sendJson(res, 404, { error: "Not found" });
    }
  }
  handlePing(res) {
    this.sendJson(res, 200, {
      status: "ok",
      vault: this.app.vault.getName()
    });
  }
  handleFolders(res) {
    const folders = [];
    const collect = (folder) => {
      if (folder.path) {
        folders.push(folder.path);
      }
      for (const child of folder.children) {
        if ("children" in child) {
          collect(child);
        }
      }
    };
    collect(this.app.vault.getRoot());
    this.sendJson(res, 200, { folders: folders.sort() });
  }
  handleTags(res) {
    const tags = Object.keys(this.cache.tags).sort();
    this.sendJson(res, 200, { tags });
  }
  async handleUpload(bodyStr, res) {
    var _a, _b;
    let body;
    try {
      body = JSON.parse(bodyStr);
    } catch (e) {
      this.sendJson(res, 400, { error: "Invalid JSON" });
      return;
    }
    if (!body.imageBase64 || !body.filename) {
      this.sendJson(res, 400, {
        error: "Missing required fields: imageBase64, filename"
      });
      return;
    }
    const sanitizedName = body.filename.replace(/[\\/:*?"<>|]/g, "_");
    const folder = ((_a = body.folder) != null ? _a : "").replace(/^\/+|\/+$/g, "");
    const filePath = folder ? `${folder}/${sanitizedName}` : sanitizedName;
    const sidecarPath = `${filePath}${Sidecar.EXTENSION}`;
    if (this.app.vault.getFileByPath(filePath)) {
      this.sendJson(res, 409, {
        error: "File already exists",
        path: filePath
      });
      return;
    }
    try {
      if (folder) {
        const existing = this.app.vault.getAbstractFileByPath(folder);
        if (!existing) {
          await this.app.vault.createFolder(folder);
        }
      }
      const sidecarContent = this.buildSidecarContent(body);
      await this.app.vault.create(sidecarPath, sidecarContent);
      const binaryString = atob(body.imageBase64);
      const bytes = new Uint8Array(binaryString.length);
      for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }
      await this.app.vault.createBinary(filePath, bytes.buffer);
      this.sendJson(res, 200, {
        success: true,
        path: filePath,
        sidecarPath
      });
    } catch (e) {
      console.error("[Media Companion API] Upload error:", e);
      this.sendJson(res, 500, {
        error: (_b = e == null ? void 0 : e.message) != null ? _b : "Upload failed"
      });
    }
  }
  buildSidecarContent(body) {
    var _a;
    const lines = ["---"];
    if (body.sourceUrl) {
      lines.push(
        `source-url: "${body.sourceUrl.replace(/"/g, '\\"')}"`
      );
    }
    if (body.sourceTitle) {
      lines.push(
        `source-title: "${body.sourceTitle.replace(/"/g, '\\"')}"`
      );
    }
    lines.push(`added: ${(/* @__PURE__ */ new Date()).toISOString()}`);
    if (body.tags && body.tags.length > 0) {
      lines.push("tags:");
      for (const tag of body.tags) {
        lines.push(`  - ${tag}`);
      }
    }
    lines.push("---");
    const template = (_a = this.plugin.settings.sidecarTemplate) == null ? void 0 : _a.trim();
    if (template) {
      lines.push("");
      lines.push(template);
    }
    return lines.join("\n") + "\n";
  }
  readBody(req) {
    return new Promise((resolve, reject) => {
      let body = "";
      let size = 0;
      const MAX_BODY_SIZE = 100 * 1024 * 1024;
      req.on("data", (chunk) => {
        const str = typeof chunk === "string" ? chunk : chunk.toString();
        size += str.length;
        if (size > MAX_BODY_SIZE) {
          req.destroy();
          reject(new Error("Request body too large"));
          return;
        }
        body += str;
      });
      req.on("end", () => resolve(body));
      req.on("error", reject);
    });
  }
  sendJson(res, status, data) {
    res.writeHead(status, { "Content-Type": "application/json" });
    res.end(JSON.stringify(data));
  }
};

// main.ts
var MediaCompanion = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.cache = new Cache(this.app, this);
    this.mutationHandler = new MutationHandler(this.app, this, this.cache);
    this.apiServer = new ApiServer(this.app, this, this.cache);
    this.registerViews();
    this.registerBasesViews();
    this.app.workspace.onLayoutReady(async () => {
      await this.cache.initialize();
      this.registerEvents();
      this.apiServer.start();
      this.app.metadataTypeManager.properties[MediaFile.last_updated_tag.toLowerCase()].type = "datetime";
    });
    this.addSettingTab(new MediaCompanionSettingTab(this.app, this));
  }
  onunload() {
    this.apiServer.stop();
  }
  registerEvents() {
    this.mutationHandler.initializeEvents();
    this.registerEvent(this.app.workspace.on("layout-change", async () => {
      const explorers = this.app.workspace.getLeavesOfType("file-explorer");
      for (const explorer of explorers) {
        await this.cache.hideAll(explorer);
      }
    }));
    let redirecting = false;
    this.registerEvent(this.app.workspace.on("active-leaf-change", (leaf) => {
      var _a, _b, _c, _d, _e;
      if (redirecting || !leaf) return;
      if (((_a = leaf.view) == null ? void 0 : _a.getViewType()) === VIEW_TYPE_SIDECAR) return;
      if (leaf.getRoot() !== this.app.workspace.rootSplit) return;
      const filePath = (_c = (_b = leaf.getViewState()) == null ? void 0 : _b.state) == null ? void 0 : _c.file;
      if (!filePath) return;
      const ext = (_e = (_d = filePath.split(".").pop()) == null ? void 0 : _d.toLowerCase()) != null ? _e : "";
      if (!this.settings.extensions.includes(ext)) return;
      redirecting = true;
      leaf.setViewState({
        type: VIEW_TYPE_SIDECAR,
        state: { file: filePath }
      }).finally(() => {
        redirecting = false;
      });
    }));
  }
  registerViews() {
    this.registerView(VIEW_TYPE_SIDECAR, (leaf) => new SidecarView(leaf));
    const alreadyRegistered = new Set(Object.keys(this.app.viewRegistry.typeByExtension));
    const newExts = this.settings.extensions.filter((ext) => !alreadyRegistered.has(ext));
    if (newExts.length > 0) {
      this.registerExtensions(newExts, VIEW_TYPE_SIDECAR);
    }
  }
  registerBasesViews() {
    this.registerBasesView(BASES_VIEW_TYPE_WATERFALL, {
      name: "Media Waterfall",
      icon: "layout-grid",
      factory: (controller, containerEl) => {
        return new WaterfallBasesView(controller, containerEl, () => this.settings);
      },
      options: () => getWaterfallViewOptions()
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.app.workspace.trigger("mc:settings-changed");
  }
};
var MediaCompanionSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    const extensionDebounce = (0, import_obsidian6.debounce)(async (value) => {
      this.plugin.settings.extensions = value.split(",").map((ext) => ext.trim()).map((ext) => ext.replace(".", "")).filter((ext) => ext.length > 0).map((ext) => ext.toLowerCase()).filter((ext) => ext !== "md");
      await this.plugin.saveSettings();
      await this.plugin.cache.updateExtensions();
    }, 500, true);
    containerEl.empty();
    new import_obsidian6.Setting(containerEl).setName("Hide sidecar files").setDesc("(Recommended) Hide sidecar files in the file explorer.").addToggle((toggle) => toggle.setValue(this.plugin.settings.hideSidecar).onChange(async (value) => {
      this.plugin.settings.hideSidecar = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian6.Setting(containerEl).setName("Extensions").setDesc("Extensions to be considered as media files, separated by commas.").addTextArea((text) => text.setPlaceholder("jpg, png, gif").setValue(this.plugin.settings.extensions.join(", ")).onChange(async (value) => {
      extensionDebounce(value);
    }));
    new import_obsidian6.Setting(containerEl).setName("Sidecar template").setDesc("The template to be used for new sidecar files.").addTextArea((text) => text.setPlaceholder("Sidecar template").setValue(this.plugin.settings.sidecarTemplate).onChange(async (value) => {
      this.plugin.settings.sidecarTemplate = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Browser Extension API" });
    if (!import_obsidian6.Platform.isDesktopApp) {
      containerEl.createEl("p", {
        text: "The API server is only available on desktop.",
        cls: "setting-item-description"
      });
    }
    new import_obsidian6.Setting(containerEl).setName("Enable API server").setDesc("Start a local HTTP server so the browser extension can communicate with this plugin. Desktop only.").addToggle((toggle) => toggle.setValue(this.plugin.settings.apiEnabled).setDisabled(!import_obsidian6.Platform.isDesktopApp).onChange(async (value) => {
      this.plugin.settings.apiEnabled = value;
      await this.plugin.saveSettings();
      this.plugin.apiServer.restart();
    }));
    new import_obsidian6.Setting(containerEl).setName("API port").setDesc("The port the API server listens on (default 27124). Requires restart.").addText((text) => text.setPlaceholder("27124").setValue(String(this.plugin.settings.apiPort)).onChange(async (value) => {
      const port = parseInt(value, 10);
      if (!isNaN(port) && port > 0 && port < 65536) {
        this.plugin.settings.apiPort = port;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian6.Setting(containerEl).setName("API key").setDesc("Optional Bearer token for authentication. Leave empty to allow unauthenticated local access.").addText((text) => text.setPlaceholder("(no key)").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value.trim();
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Waterfall View" });
    new import_obsidian6.Setting(containerEl).setName("Fullscreen preview").setDesc("How the fullscreen preview is triggered from the waterfall view.").addDropdown((dropdown) => dropdown.addOption("off", "Off").addOption("hover", "Hover").addOption("click", "Click").setValue(this.plugin.settings.fullscreenMode).onChange(async (value) => {
      this.plugin.settings.fullscreenMode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian6.Setting(containerEl).setName("Fullscreen hover delay").setDesc("How long (in ms) to hover over the preview icon before the fullscreen opens. Only applies in hover mode.").addSlider((slider) => slider.setLimits(200, 3e3, 100).setValue(this.plugin.settings.fullscreenHoverDelay).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.fullscreenHoverDelay = value;
      await this.plugin.saveSettings();
    }));
  }
};

/* nosourcemap */